[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sukuk = "GS18oFeFhDvUzuiVEoe1HTT7gGMhULy2RZzLZibzs4Zd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 1000000 tests/*.ts"
